# Generated by Django 4.2.11 on 2024-12-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_alter_idea_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.CharField(choices=[('pending', 'Czekam na recenzję'), ('accepted', 'Przyjęty'), ('rejected', 'Odrzucony')], default='pending', max_length=30),
        ),
    ]
