# Generated by Django 4.2.11 on 2024-12-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_alter_idea_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ogloszenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('duration', models.DurationField()),
                ('available_spots', models.PositiveIntegerField()),
            ],
        ),
    ]
