# Generated by Django 4.2.11 on 2024-12-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_alter_ogloszenia_duration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ogloszenia',
            new_name='Szkolenia',
        ),
    ]
